#!/usr/bin/env bash
#configure subdomain for my web servers

subdomains=("www" "lb-01" "web-02")
domain="$1"
sub="$2"

dns_configuration () {
	sub="$2"
	INFO="$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR==2')"
	IP=$(echo "$INFO" | awk '{print $5}')
	RECORD=$(echo "$INFO" | awk '{print $4}')

	echo -e "The subdomain $sub is a $RECORD record and points to $IP"
}
if [ $# -eq 1 ]: then
	for subs in "${subdomains[@]}"; do
		dns_configuration"$domain" "$subs"
	done
elif [ $# -eq 2 ]; then
	dns_configuration "$domain" "$sub"
fi
