#!/usr/bin/env bash
# Install nginx and start it
apt-get -y install nginx

# Firewall setting: Allow Nginx to serve on HTTP
ufw allow 'Nginx HTTP'

# Override the default index file served as home page
echo "Hello World" >> /var/www/html/index.nginx-debian.html

# Redirect to /redirect_me to a youtube video
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Ella7d permanent;/" /etc/nginx/sites-available/default
service nginx start

